// Code generated by "stringer -type=KillReason,ReportReason -output enum_string.go"; DO NOT EDIT.

package proto

import "fmt"

const _KillReason_name = "TimeoutMemorySignal"

var _KillReason_index = [...]uint8{0, 7, 13, 19}

func (i KillReason) String() string {
	i -= 1
	if i < 0 || i >= KillReason(len(_KillReason_index)-1) {
		return fmt.Sprintf("KillReason(%d)", i+1)
	}
	return _KillReason_name[_KillReason_index[i]:_KillReason_index[i+1]]
}

const _ReportReason_name = "SuccessFailureAlertAlertRateMemoryWarningTimeWarningFileNotCreatedKilledStart"

var _ReportReason_index = [...]uint8{0, 7, 14, 19, 28, 41, 52, 66, 72, 77}

func (i ReportReason) String() string {
	i -= 1
	if i < 0 || i >= ReportReason(len(_ReportReason_index)-1) {
		return fmt.Sprintf("ReportReason(%d)", i+1)
	}
	return _ReportReason_name[_ReportReason_index[i]:_ReportReason_index[i+1]]
}
