// Code generated by go generate; DO NOT EDIT.
// This file was created by calibrate.go at
// 2020-02-12 08:45:28.320314976 -0500 EST m=+5273.249564904
// These constants are determined by monte carlo to yield a desired Type I error rate for long running statistics
package stat

const (
	LogNormalA float64 = 17.633792324895346
	LogNormalB float64 = -3.9288603662670885
	PoissonA float64 = 19.19575770635499
	PoissonB float64 = -4.069410457800821
)
